# Generated by Django 5.2.6 on 2025-10-01 07:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_customuser_nickname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('cwe', models.CharField(blank=True, max_length=50, null=True)),
                ('cvss_score', models.DecimalField(blank=True, decimal_places=1, help_text='CVSS v3.1 (0.0–10.0)', max_digits=3, null=True)),
                ('description', models.TextField()),
                ('impact', models.TextField(blank=True, null=True)),
                ('poc_file', models.FileField(blank=True, help_text='Завантаж файл з PoC (скрипт/архів/відео/скрін тощо)', null=True, upload_to='reports/poc/')),
                ('status', models.CharField(choices=[('new', 'New'), ('in_review', 'In Review'), ('resolved', 'Resolved'), ('rejected', 'Rejected')], default='new', max_length=20)),
                ('rating', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='api_report_status_a305b9_idx'), models.Index(fields=['cwe'], name='api_report_cwe_23744d_idx')],
            },
        ),
    ]
